services:
  dashboard:
    image: python:3.12-slim-bullseye
    ports:
      - 8001:8001
    depends_on:
      - data-provider
    volumes:
      - ./dashboard_service:/app/dashboard_service
    command: sh -c "cd /app/dashboard_service && bash start_server.sh"
    networks:
      - localnetwork

  data-provider:
    image: python:3.12-slim-bullseye
    ports:
      - 8000:8000
    volumes:
      - ./data_provider:/app/data_provider
    command: sh -c "cd /app/data_provider && bash start_server.sh"
    networks:
          - localnetwork

networks:
  localnetwork:
    driver: bridge
